/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl:
    process.env.NEXT_PUBLIC_BASE_URL ||
    process.env.NEXT_PUBLIC_SITE_URL ||
    'https://www.arcmeninterior.com',

  generateRobotsTxt: true,
  sitemapSize: 50000,
  outDir: './public',
  changefreq: 'monthly',
  priority: 0.7,

  exclude: [
    '/admin-panel',
    '/admin-panel/*',
    '/login',
    '/registration',
    '/otp-verification',
    '/forgot-password',
    '/private',
    '/private/*',
    '/api',
    '/api/*',
    '/thank-you',
    '/interior-designers-chennai/thank-you',
    '/sitemap.xml',
    '/robots.txt',

    // Legacy URLs migrated to client-approved URLs
    '/mr-raja-family',
    '/mr-baskaran-family',
    '/mr-raguraman-family',
    '/mr-mohan-family',
    '/mr-manikandan-family',
    '/mr-dhanasekar-family',
    '/mr-santhosh-family',
    '/mr-harish-family',
    '/mr-kandhan-family',
    '/mrs-mohan',
    '/nbs-vijay-shankar-family',
    '/3bhk-apartment-adayar-interior',
    '/3bhk-apartment-velacherry-interior',
    '/individual-house-kknagar-interior',
    '/individual-duplex-house-annanagar-interior',
    '/individual-house-perambur-interior',
    '/elevation-design-architectural',
    '/interior-design-architectural',
    '/interior-design-valasaravakkam-architectural',
    '/living-room-double-height-interior-design-architectural',
    '/duplex-house-elevation-design-architectural',
    '/duplux-house-elevation-design-peravurani-architectural',
    '/pool-terrace-design-architectural',
    '/bedroom-interior-design-architectural',
    '/duplex-house-elevation-design-nolambur-architectural',
    '/duplex-villa-elevation-design-architectural',
    '/house-of-glass-front-elevation-design-architectural',
    '/villa-landscape-design-architectural',
    '/row-house-architectural',
    '/villa-elevation-design-sadik-architectural',
    '/duplex-house-elevation-design-front-ayyampettai-architectural',
    '/interior-designing-company-in-chennai',
    '/modular-kitchen',
    '/architectural-projects/individual-house-kknagar-interior',
  ],

  robotsTxtOptions: {
    policies: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/admin-panel/',
          '/login',
          '/registration',
          '/otp-verification',
          '/forgot-password',
          '/private/',
          '/api/',
          '/thank-you',
        ],
      },
    ],
  },

  additionalPaths: async () => [
    ...[
      '/interior-design-projects/mrs-nithya-srinivasan',
      '/interior-design-projects/mr-rama-elangovan',
      '/interior-design-projects/mr-srinath-kanya',
      '/interior-design-projects/mr-arun-dev',
      '/interior-design-projects/mrs-porchelvi',
      '/architectural-projects/elevation-design-architectural',
      '/architectural-projects/interior-design-architectural',
      '/architectural-projects/interior-design-valasaravakkam-architectural',
      '/architectural-projects/living-room-double-height-interior-design-architectural',
      '/architectural-projects/duplex-house-elevation-design-architectural',
      '/architectural-projects/duplux-house-elevation-design-peravurani-architectural',
      '/architectural-projects/pool-terrace-design-architectural',
      '/architectural-projects/bedroom-interior-design-architectural',
      '/architectural-projects/duplex-house-elevation-design-nolambur-architectural',
      '/architectural-projects/duplex-villa-elevation-design-architectural',
      '/architectural-projects/house-of-glass-front-elevation-design-architectural',
      '/architectural-projects/villa-landscape-design-architectural',
      '/architectural-projects/row-house-architectural',
      '/architectural-projects/villa-elevation-design-sadik-architectural',
      '/architectural-projects/duplex-house-elevation-design-front-ayyampettai-architectural',
    ].map((loc) => ({
      loc,
      changefreq: 'monthly',
      priority: 0.7,
    })),
    {
      loc: '/contact-us',
      changefreq: 'monthly',
      priority: 0.8,
    },
  ],
};